#ifndef _PLUG_LANG_H_
#define _PLUG_LANG_H_

enum
{
	MSG_PLUGIN_NAME,
	MSG_PLUGIN_CONFIG_NAME,
	// Configuration
	MSG_CONFIG_TITLE,
	MSG_CONFIG_ENABLE,
	MSG_CONFIG_PREFIX,
	MSG_CONFIG_USEEXTFILTERS,
	//Info lines
	MSG_INFOL_FORMAT,
	MSG_INFOL_COMPRESSION,
	MSG_INFOL_COMMENT,
	MSG_INFOL_CREATED,
	MSG_INFOL_FILES,
	MSG_INFOL_DIRS,
	MSG_INFOL_SIZE,
	// Extraction
	MSG_EXTRACT_TITLE,
	MSG_EXTRACT_CONFIRM,
	MSG_EXTRACT_ERROR,
	MSG_EXTRACT_DIR_CREATE_ERROR,
	MSG_EXTRACT_OVERWRITE,
	MSG_EXTRACT_FAILED,
	MSG_EXTRACT_EXTRACTING,
	MSG_EXTRACT_NODISKSPACE,
	MSG_EXTRACT_DEFOVERWRITE,
	MSG_EXTRACT_KEEPPATHS,
	// Open storage
	MSG_OPEN_LIST,
	MSG_OPEN_CONTENT_ERROR,
	MSG_OPEN_INVALID_ITEM,
	// Buttons
	MSG_OVERWRITE,
	MSG_OVERWRITE_ALL,
	MSG_SKIP,
	MSG_SKIP_ALL,
	MSG_BTN_CANCEL,
	MSG_BTN_EXTRACT,
	//Key bar
	MSG_ALTF6
};

#endif
