#ifndef _PLUG_LANG_H_
#define _PLUG_LANG_H_

enum
{
	MSG_PLUGIN_NAME,
	MSG_PLUGIN_CONFIG_NAME,
	// Configuration
	MSG_CONFIG_TITLE,
	MSG_CONFIG_PREFIX,
	MSG_CONFIG_USEEXTFILTERS,
	MSG_CONFIG_OPEN_ON_ENTER,
	MSG_CONFIG_OPEN_ON_CTRL_PGDN,
	MSG_CONFIG_OPEN_ON_BOTH,
	//Info lines
	MSG_INFOL_FORMAT,
	MSG_INFOL_COMPRESSION,
	MSG_INFOL_COMMENT,
	MSG_INFOL_CREATED,
	MSG_INFOL_FILES,
	MSG_INFOL_DIRS,
	MSG_INFOL_SIZE,
	MSG_INFOL_PACKEDSIZE,
	// Extraction
	MSG_EXTRACT_TITLE,
	MSG_EXTRACT_CONFIRM,
	MSG_EXTRACT_ERROR,
	MSG_EXTRACT_DIR_CREATE_ERROR,
	MSG_EXTRACT_OVERWRITE,
	MSG_EXTRACT_FAILED,
	MSG_EXTRACT_EXTRACTING,
	MSG_EXTRACT_NODISKSPACE,
	MSG_EXTRACT_DEFOVERWRITE,
	MSG_EXTRACT_KEEPPATHS,
	MSG_EXTRACT_PROGRESS_FILES,
	MSG_EXTRACT_PROGRESS_BYTES,
	MSG_EXTRACT_PROGRESS_ELAPSED,
	// Open storage
	MSG_OPEN_LIST,
	MSG_OPEN_CONTENT_ERROR,
	MSG_OPEN_INVALID_ITEM,
	MSG_OPEN_SELECT_MODULE,
	MSG_OPEN_PASS_REQUIRED,
	MSG_OPEN_FILE,
	MSG_OPEN_FILE_AS,
	// Buttons
	MSG_OVERWRITE,
	MSG_OVERWRITE_ALL,
	MSG_BTN_SKIP,
	MSG_BTN_SKIP_ALL,
	MSG_BTN_OK,
	MSG_BTN_CANCEL,
	MSG_BTN_EXTRACT,
	MSG_BTN_ABORT,
	MSG_BTN_RENAME,
	// Dialogs
	MSG_TITLE_WARNING,
	MSG_TITLE_RENAME,
	MSG_DLG_REMEMBER,
	MSG_DLG_NEWFILENAME,
	MSG_DLG_OLDFILE_INFO,
	MSG_DLG_NEWFILE_INFO,
	// Key bar
	MSG_ALTF6,
	// Node Properties
	MSG_PROPS_HEADER,
	MSG_PROPS_PATH,
	MSG_PROPS_SIZE,
	MSG_PROPS_PACKEDSIZE,
	MSG_PROPS_ATTRIBUTES,
	MSG_PROPS_CREATETIME,
	MSG_PROPS_MODIFYTIME,
	MSG_PROPS_OWNER,
	MSG_PROPS_HARDLINKS
};

#endif
